### ISSUE TITLE
hello-world and update

### ISSUE THREAD

**Issue by Keyrxng** [ubiquibot/plugin-template#14]
Create a `hello-world` plugin and bring the template up to date

- fix ci
- update logger
- create a minimal but well-rounded example
- improve test env with helpers and handlers
- add tests for example plugin demo-ing structure

I think we should remove supabase etc all together as it's being phased out and when I start a fresh plugin my first move is to remove it

**Comment by 0x4007** [comment]
> I think we should remove supabase etc all together as it's being phased out and when I start a fresh plugin my first move is to remove it

Great idea.
