### ISSUE TITLE
Near Instant GitHub Actions Cold Boot Times

### ISSUE THREAD

**Issue by 0x4007** [ubiquibot/plugin-template#24]
I got TypeScript to run from a cold boot in 4s via GitHub Actions to post a test comment [on pr push](https://github.com/0x4007/github-script/pull/1#issuecomment-2383959605). This gives a lot of strength to GitHub Actions based plugins, dropping our response times from ~30s to 4s. 

Upon further research, I see they made a TypeScript Action template leveraging all of these technologies. Using its minimal example, I got a [log response in 3s](https://github.com/0x4007/typescript-action/actions/runs/11113036703/job/30876441750).

### Task

1. Fork https://github.com/actions/typescript-action
2. Include our `ts-template` settings

###

Archived logs from my first run:

<img width="332" alt="image" src="https://github.com/user-attachments/assets/ee582e7d-0a76-410a-860a-3eb020719c8c">

[logs_29033792543.zip](https://github.com/user-attachments/files/17195485/logs_29033792543.zip)

**Comment by 0x4007** [comment]
Current research status: figuring out how to auth as github-actions https://github.com/0x4007/typescript-action/pull/1 and seeing if I can post on the pull and how long that will take.

**Comment by 0x4007** [comment]
@gentlementlegen wondering if I should close as unplanned. It seems like you got it working with `ncc`

This task implied that we would also inherit all of GItHub's CI in https://github.com/actions/typescript-action which looks extremely proper and could be good! But is not the primary objective of this task.

**Comment by gentlementlegen** [comment]
@0x4007 I guess we can have this task to make sure all the repos use it?

For the CI actually I think I reimplemented all by accident in https://github.com/ubiquity-os/action-deploy-plugin
There is
- semantic versioning
- build
- and customized inputs for our needs

Only missing thing is the testing but I did not use any TypeScript so far, so was not needed.

Shall I assign myself to this?

**Comment by 0x4007** [comment]
If you can take the GitHub @action team's CI then yes it would be great if you can take this over. That is my intention. as you can imagine, they are top tier in making use of GitHub Actions and we have a lot to learn/adopt from their implementations.

**Comment by 0x4007** [comment]
@gentlementlegen should we close as unplanned? It seems like you might have already figured this one out mostly.

**Comment by gentlementlegen** [comment]
@0x4007 we can, however this is not implement within all of our action plug-ins.
