### ISSUE TITLE
Add `url` property to `manifest.json`

### ISSUE THREAD

**Issue by rndquu** [ubiquibot/plugin-template#33]
We need to know an exact plugin URL (in case it works as a cloudflare worker) in order to set it in the partner [onboarding](https://github.com/ubiquity-os/ubiquity-os-plugin-installer) UI.

What should be done:
1. Add a new optional `url` property to [manifest.json](https://github.com/ubiquity-os/plugin-template/blob/8d8f06958ca1273f299ae0bc2a51a6c512411af9/manifest.json)
2. Update the [worker-deploy.yml](https://github.com/ubiquity-os/plugin-template/blob/8d8f06958ca1273f299ae0bc2a51a6c512411af9/.github/workflows/worker-deploy.yml) workflow to set the `url` property in `manifest.json` on each deployment of the `development` branch. I think it's enough for now to use the `development` plugin instances + https://github.com/ubiquity-os/ubiquity-os-plugin-installer will simply have to fetch a default plugin's github branch in order to get a plugin URL.
3. Make sure all plugins from https://github.com/ubiquity-os-marketplace have the `url` property set in the `manifest.json` file and updated [worker-deploy.yml](https://github.com/ubiquity-os/plugin-template/blob/8d8f06958ca1273f299ae0bc2a51a6c512411af9/.github/workflows/worker-deploy.yml) workflow

Original [comment](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/24#issuecomment-2493899154)

**Comment by rndquu** [comment]
@gentlementlegen Pls check the description

**Comment by gentlementlegen** [comment]
How do we deal with plugins that offers both Actions and Workers like the telegram chatroom?

**Comment by rndquu** [comment]
> How do we deal with plugins that offers both Actions and Workers like the telegram chatroom?

I don't have much context on the telegram kernel but it seems the plugin architecture must be optimized if it requires both github action and a worker.

**Comment by Keyrxng** [comment]
> How do we deal with plugins that offers both Actions and Workers like the telegram chatroom?

We could do: `manifest.urls.action: ...`

> I don't have much context on the telegram kernel but it seems the plugin architecture must be optimized if it requires both github action and a worker.

It's split into worker/action because we needed a node env to run MTProto API to implement the `chatroom` feature. 

It should be converted to a [single worker plugin](https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/issues/20) like it was originally now that 0x4007 decided to export the `KERNEL_PRIVATE_KEY` as an org secret,, so it can be simplified in the sense of it requiring only one config entry.

**Comment by rndquu** [comment]
@gentlementlegen I need you blessing on this task.

I think plugins that work both as a worker and a github action are outliers and it's safe to introduce the `url` property in the `manifest.json` file.

**Comment by gentlementlegen** [comment]
Sure, we only have one edge case so far. Maybe we can think of an option later like "install as Worker" and "install as Action". We can safely introduce the url property in the meantime.

**Comment by whilefoo** [comment]
> We need to know an exact plugin URL (in case it works as a cloudflare worker) in order to set it in the partner [onboarding](https://github.com/ubiquity-os/ubiquity-os-plugin-installer) UI.

How will the onboarding UI know if the plugin is a worker or action?
We could have https:// if it's a worker and github://ubiquity-os/marketplace@main if it's an action

We could also have `urls` property that would have 2 urls for hybrid plugins but that would also require changes in the kernel.

> It's split into worker/action because we needed a node env to run MTProto API to implement the `chatroom` feature.
> 
> It should be converted to a [single worker plugin](https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/issues/20) like it was originally now that 0x4007 decided to export the `KERNEL_PRIVATE_KEY` as an org secret,, so it can be simplified in the sense of it requiring only one config entry.

Don't we still need node runtime for MTPRroto, so how can we convert to single worker plugin?

**Comment by rndquu** [comment]
> How will the onboarding UI know if the plugin is a worker or action?

If the `url` property is present in the `manifest.json` file then it's a worker

> Don't we still need node runtime for MTPRroto, so how can we convert to single worker plugin?

@Keyrxng knows better

**Comment by 0x4007** [comment]
> We need to know an exact plugin URL (in case it works as a cloudflare worker) in order to set it in the partner onboarding UI.

This is no longer the case so perhaps this can be closed as unplanned.

**Comment by rndquu** [comment]
> > We need to know an exact plugin URL (in case it works as a cloudflare worker) in order to set it in the partner onboarding UI.
> 
> This is no longer the case so perhaps this can be closed as unplanned.

How to get a plugin URL for a 3rd party plugin created by some other developer?

**Comment by 0x4007** [comment]
I don't have full context on this repository but specifically in the plugin installer UI I fixed this problem.

**Comment by gentlementlegen** [comment]
The problem is that the plugin installer cannot guess the URL to put it in the configuration which is the problem. It only knows the GitHub repository. One workaround would be if we had deployment urls linked within the github repo we could use these.

**Comment by rndquu** [comment]
> The problem is that the plugin installer cannot guess the URL to put it in the configuration which is the problem. It only knows the GitHub repository. One workaround would be if we had deployment urls linked within the github repo we could use these.

Then we also have to force partners to setup github deployment URLs which might not be the too convenient for them.

A single `url` property is basically a "set and forget" approach when partners set plugin URL in the `manifest.json` only once to the production URL and never(?) get back to it.

**Comment by gentlementlegen** [comment]
The schema for start/stop has changed and it is not up to date here which is why the command didn't work. fixing.

**Comment by whilefoo** [comment]
Also we can still support raw https URLs, so if it's a https URL then we call it directly but when it's set to `org/repo` we can retrieve the manifest which we already need for other things, and check if `url` is present then we call that otherwise trigger the workflow

**Comment by gentlementlegen** [comment]
At this time I just set the URL for Workers. Do we want to have the `org/repo` within that field when it is an Action? I can, as long as everyone agrees on this.

**Comment by whilefoo** [comment]
> At this time I just set the URL for Workers. Do we want to have the `org/repo` within that field when it is an Action? I can, as long as everyone agrees on this.

I meant if `org/repo` is set in the repo config, for manifest we can tell if it's Action if url is not present

**Comment by gentlementlegen** [comment]
My understanding is that it happens the other way around:
the plugin installer needs to know if the plugin you're installing should be treated as a worker / action, so that it generates the proper value in the `ubiquity-os.config.yml` file by settings either a url to the worker, or a `org/repo` instead, which is why we need the URL in the manifest to be present.

**Comment by 0x4007** [comment]
Then why don't we just try calling it as an external url first and if it fails then run as action

**Comment by gentlementlegen** [comment]
How do you guess the deployment url? This is why the proposal makes it populated during the deployment step

**Comment by whilefoo** [comment]
> My understanding is that it happens the other way around:
> the plugin installer needs to know if the plugin you're installing should be treated as a worker / action, so that it generates the proper value in the `ubiquity-os.config.yml` file by settings either a url to the worker, or a `org/repo` instead, which is why we need the URL in the manifest to be present.

This is a fine approach but another way would be that plugin installer sets `org/repo` in the `ubiquity-os.config.yml` and the kernel will check the URL in the manifest or the lack of URL would imply it's an Action. (anyway the kernel already fetches the manifest).

This way we also solve the problem with changing URLs, because if the URL is in the manifest then the kernel can check it and you don't need to update URLs.

I was only addressing @0x4007 concern that we couldn't use closed-source plugins anymore, but it's not true because you could still specify a https URL in the `ubiquity-os.config.yml`.

**Comment by gentlementlegen** [comment]
@whilefoo I like this idea because that would streamline the configuration file which would only contain `org/repo` for any plugin, and you would never have to think about "is this a plugin or a worker".

However we have that one plugin for telegram that uses both, but that's the only one (we might want to look into it to change that).

**Comment by 0x4007** [comment]
I don't think we should make accommodations based on the telegram plugin architecture. 

To be honest I haven't been able to benefit from it, like subscribing to events never worked etc. there's a high chance it will be completely redone in the future.

**Comment by rndquu** [comment]
> > My understanding is that it happens the other way around:
> > the plugin installer needs to know if the plugin you're installing should be treated as a worker / action, so that it generates the proper value in the `ubiquity-os.config.yml` file by settings either a url to the worker, or a `org/repo` instead, which is why we need the URL in the manifest to be present.
> 
> This is a fine approach but another way would be that plugin installer sets `org/repo` in the `ubiquity-os.config.yml` and the kernel will check the URL in the manifest or the lack of URL would imply it's an Action. (anyway the kernel already fetches the manifest).
> 
> This way we also solve the problem with changing URLs, because if the URL is in the manifest then the kernel can check it and you don't need to update URLs.
> 
> I was only addressing @0x4007 concern that we couldn't use closed-source plugins anymore, but it's not true because you could still specify a https URL in the `ubiquity-os.config.yml`.

Added 2 tasks, for the kernel and UI installer:
- https://github.com/ubiquity-os/ubiquity-os-kernel/issues/224
- https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/39

**Comment by gentlementlegen** [comment]
I will updat all the related plugins that should be treated as workers and link the pull-requests here.

**Comment by gentlementlegen** [comment]
- https://github.com/ubiquity-os-marketplace/command-wallet/pull/30
- https://github.com/ubiquity-os-marketplace/command-start-stop/pull/111
- https://github.com/ubiquity-os-marketplace/command-query/pull/30
- https://github.com/ubiquity-os-marketplace/text-vector-embeddings/pull/62

I think that's all?

**Comment by rndquu** [comment]
> * [chore: update deployment workflow ubiquity-os-marketplace/command-wallet#30](https://github.com/ubiquity-os-marketplace/command-wallet/pull/30)
> * [feat: deploy url ubiquity-os-marketplace/command-start-stop#111](https://github.com/ubiquity-os-marketplace/command-start-stop/pull/111)
> * [feat: deploy url ubiquity-os-marketplace/command-query#30](https://github.com/ubiquity-os-marketplace/command-query/pull/30)
> 
> I think that's all?

https://github.com/ubiquity-os-marketplace/text-vector-embeddings ?

**Comment by gentlementlegen** [comment]
I think this is supposed to be a long-running Action? rfc @sshivaditya2019

**Comment by rndquu** [comment]
> I think this is supposed to be a long-running Action? rfc @sshivaditya2019

Right now it is [set as a worker](https://github.com/ubiquity-os/.ubiquity-os/blob/67df7f5643edcaa3899304481f7ff4ef74a1041a/.github/.ubiquity-os.config.dev.yml#L3)

**Comment by gentlementlegen** [comment]
And it is set as an [Action](https://github.com/ubiquity-os-marketplace/.ubiquity-os/blob/main/.github/.ubiquity-os.config.dev.yml#L425) (actually it is set even [twice](https://github.com/ubiquity-os-marketplace/.ubiquity-os/blob/main/.github/.ubiquity-os.config.dev.yml#L342)). My guess is that it started as a Worker but was a long running process and eventually moved to an Action.

Seems to run fine as an Action: https://github.com/ubiquity-os-marketplace/text-vector-embeddings/actions/workflows/compute.yml

**Comment by rndquu** [comment]
> And it is set as an [Action](https://github.com/ubiquity-os-marketplace/.ubiquity-os/blob/main/.github/.ubiquity-os.config.dev.yml#L425) (actually it is set even [twice](https://github.com/ubiquity-os-marketplace/.ubiquity-os/blob/main/.github/.ubiquity-os.config.dev.yml#L342)). My guess is that it started as a Worker but was a long running process and eventually moved to an Action.
> 
> Seems to run fine as an Action: https://github.com/ubiquity-os-marketplace/text-vector-embeddings/actions/workflows/compute.yml

In other orgs it's set as a worker ([one](https://github.com/ubiquity/.ubiquity-os/blob/51a65e28cc7bf94ff07907c115c7b6d9c9d84777/.github/.ubiquity-os.config.yml#L405), [two](https://github.com/ubiquity-os/.ubiquity-os/blob/67df7f5643edcaa3899304481f7ff4ef74a1041a/.github/.ubiquity-os.config.dev.yml#L3)).

@sshivaditya2019 How should https://github.com/ubiquity-os-marketplace/text-vector-embeddings plugin be set, as a worker or a github action? Or it doesn't matter?

Overall, as far as I remember, the general concept was that for "easy" plugins that run fast we use workers while for long running plugins we use github actions. https://github.com/ubiquity-os-marketplace/text-vector-embeddings basically saves data to a DB on a request so it falls in the "easy" plugins section.

**Comment by gentlementlegen** [comment]
Now that our plugins use the SDK and `hono` basically all can run on either workers or actions so indeed it just depends on their run duration. I am fine having it as a worker as long as it is fast! Will open a PR then.

**Comment by whilefoo** [comment]
It seems to run only 10 seconds but I would keep it as an Action because Cloudflare has tight time limits so it might timeout and we don't need it to be fast because it's not responding to users

**Comment by gentlementlegen** [comment]
Worst case we can just disable the workflow that deploys to cloudflare and remove the url from the manifest to get it back as actions.

**Comment by Keyrxng** [comment]
> However we have that one plugin for telegram that uses both, but that's the only one (we might want to look into it to change that).

> I don't think we should make accommodations based on the telegram plugin architecture.

> To be honest I haven't been able to benefit from it, like subscribing to events never worked etc. there's a high chance it will be completely redone in the future.

lol guys I have said it like 5 times now. @0x4007 exposed the private key via org secrets after it holding back the telegram bot for a week or so in debate, so it doesn't need to exist like it does now.

It ONLY exists like that because review pushed me that way but it _should_ be a single worker entry.

---

Glad you came to a resolution with it @gentlementlegen

**Comment by 0x4007** [comment]
> so it doesn't need to exist like it does now. 

You can file a proposal so we can fix it

**Comment by Keyrxng** [comment]
> > so it doesn't need to exist like it does now.
> 
> You can file a proposal so we can fix it

https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/issues/20

Been open for ages
