### ISSUE TITLE
Update `eslint` to `v9`

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/plugin-template#5]
We are using an old version of `eslint` which differs in the way of how the configuration is defined. A new format called `flat format` is now in used, and has benefits like having a fully type supported `typescript` check within the configuration. It would be nice to benefit from that upgrade for the new plugins.

References:
https://eslint.org/docs/latest/use/migrate-to-9.0.0
https://typescript-eslint.io/getting-started

**Comment by 0x4007** [comment]
I guess the rewards calculation for the pull comments are very broken this time @gentlementlegen 

When v2?

**Comment by gentlementlegen** [comment]
@0x4007 Seems v2 went on a break as well, I do not see anymore logs. Might be because it's not using the main branch for deployments (I think I sent you a message about this). Waiting of `start | stop` then good to go.
https://github.com/ubiquibot/command-start-stop/pull/1
