### ISSUE TITLE
Plugin onboarding

### ISSUE THREAD

**Issue by gitcoindev** [ubiquibot/plugin-template#7]
As discussed via Telegram with @0x4007 , the goal of this issue is to write a 'Hello world' plugin to ensure that the documentation is without errors and clear enough to onboard new developers who have no previous experience with the repository.

**Comment by 0x4007** [comment]
Also I encourage you to write proposals to streamline the process further as you see fit. 

We want to make things as simple as possible for new developers and I'm sure that there's lots of low hanging fruit.

**Comment by 0x4007** [comment]
To clarify, by proposals I mean file new GitHub issues under the appropriate repositories specifying new tasks to enhance the onboarding.
